/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FirstName = string;
export type LastName = string;
export type Email = string;
export type CountryOfCitizenship = "United States" | "Canada" | "United Kingdom" | "Other";
export type LinkedInPersonalWebsiteURL = string;
/**
 * Upload your resume or CV to help us better understand your background
 */
export type Resume = string;
export type VisaCategoriesOfInterest = ("O-1" | "EB-1A" | "EB-2 NIW" | "I don't know")[];
/**
 * Tell us about your background, what is your past immigration history? Can you work in the US? Are you currently employed? What are your goals? What is your timeline for filing?
 */
export type HowCanWeHelpYou = string;

export interface LeadSchema {
  firstName: FirstName;
  lastName: LastName;
  email: Email;
  country: CountryOfCitizenship;
  linkedIn?: LinkedInPersonalWebsiteURL;
  resume: Resume;
  visaCategory: VisaCategoriesOfInterest;
  details: HowCanWeHelpYou;
  [k: string]: unknown;
}
